let trilho = document.getElementById('trilho')
let form = document.querySelector('form')
let body = document.querySelector('body')
let pass = document.querySelector('.pass')
let login = document.querySelector('.login')
let go = document.querySelector('.go')
let signup = document.querySelector('.signup')
let i = document.querySelector('i')
let h1 = document.querySelector('h1')
let h4 = document.querySelector('h4')
let p = document.querySelector('p')
let container = document.querySelector('.container')
let alienBlue = document.querySelector('.blueAlienjs')
let keyBlue = document.querySelector('.blueKeyjs')

trilho.addEventListener('click', () => {
    trilho.classList.toggle('light')
    form.classList.toggle('light')
    body.classList.toggle('light')
    login.classList.toggle('light')
    pass.classList.toggle('light')
    go.classList.toggle('light')
    signup.classList.toggle('light')
    i.classList.toggle('light')
    p.classList.toggle('light')
    h1.classList.toggle('light')
    h4.classList.toggle('light')
    container.classList.toggle('light')
    alienBlue.classList.toggle('light')
    keyBlue.classList.toggle('light')
})